// This file is typically auto-generated by the Amplify CLI
// This is a placeholder that would be replaced with actual configuration

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'PLACEHOLDER_IDENTITY_POOL_ID',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'PLACEHOLDER_USER_POOL_ID',
  aws_user_pools_web_client_id: 'PLACEHOLDER_WEB_CLIENT_ID',
  oauth: {},
  aws_appsync_graphqlEndpoint: 'PLACEHOLDER_GRAPHQL_ENDPOINT',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile; 